name: Logtail python client

on:
  - push
  - pull_request

jobs:
  build:
    # As long as we need Python 2.7 here in the test, we can only use up to Ubuntu 20.
    # https://github.com/rwth-i6/returnn/issues/1226
    # 20.04 is a LTS with 2030 support EOL 
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ['2.7', '3.5', '3.6', '3.7', '3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Test with tox
      run: tox
